[nitpick]

[nitpick.files.present]


["setup.cfg"."metadata"]
version = "attr: humblebundle_to_sqlite.__version__"


["setup.cfg"."tool:pytest"]
cache_dir = ".cache/pytest"
markers = "acceptance: marker for acceptance tests."
addopts = "--strict-config --strict-markers --doctest-modules --cov --cov-report=term-missing"
#--ignore=src/package_name/__main__.py
#--tb=short


["setup.cfg"."coverage:run"]
branch = true
source = "."
omit = "setup.py"
data_file = ".cache/coverage"


["setup.cfg".mypy]
strict = true
pretty = true
cache_dir = ".cache/mypy"
#show_column_numbers = true
#show_error_codes = true
#show_error_context = true


["setup.cfg".mypy-setuptools]
ignore_missing_imports = true


["setup.cfg".flake8]
show-source = true
doctests = true
max-line-length = 88
max-complexity = 6
#statistics = false

select = "B, B9, C, E, F, S, W"
# B: Bugbear
# B9: Bugbear opinions
# C: Complexity (McCabe)
# E: Errors (pycodestyle)
# F: Fatals (PyFlakes)
# S: Security (Bandit)
# W: Warnings (pycodestyle)
# Note: Flake8-Bandit codes start with S because B is reserved by Bugbear

per-file-ignores = "test/*:S101"
# E501 is handeled by B950
ignore = "E501"
# B008: Do not perform function calls in argument defaults.
# B950: Line too long (line is > max-line-length + 10%)
# E203: Whitespace before ':', not PEP 8 compliant
# E266: Too many leading '#' for block comment
# E402: Import at top, too many circular import fixes
# E501: Line too long (strict max-line-length)
# E722: Bare except, handled by Bugbear B001
# F811: Redefinition of unused function/method
# S101: Use of assert detected.
# S404: import_subprocess
# S603: Test for use of subprocess without shell equals true
# W503: Line break before binary operator, not PEP 8 compliant
