---

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: 38b88246ccc552bffaaf54259d064beeee434539  # frozen: v4.0.1
    hooks:
      - id: detect-private-key
        name: Detect private key
      - id: end-of-file-fixer
        name: Fix end of files
      - id: fix-byte-order-marker
        name: Fix utf-8 byte order marker
      - id: trailing-whitespace
        name: Trim trailing whitespace

  - repo: local
    hooks:
      - id: lint-nitpick
        name: Lint project config files
        language: system
        entry: nitpick --offline check
        types: [ini]

      - id: lint-mypy
        name: Lint static typing
        language: system
        entry: mypy
        types: [python]

      - id: lint-flake8
        name: Lint flake8
        language: system
        entry: flake8
        types: [python]

      - id: lint-black
        name: Lint code formatting
        language: system
        entry: black --check --diff --color --experimental-string-processing
        types: [python]

      - id: test-pytest
        name: Run test suite
        language: system
        entry: pytest
        pass_filenames: false
        always_run: true
